[package]
name = "code_generator"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
codegen = "0.2.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
serde_path_to_error = "0.1.20"
serde_repr = "0.1.20"
